config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  root to: 'pages#home'
  devise_for :users
  # resources :users
  resources :bookings, only: %i[index show destroy]
  resources :services do
    collection do
      get :genre
    end
    resources :bookings, only: %i[new create]
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/booking.rb
class Booking < ApplicationRecord
  belongs_to :user
  belongs_to :service

  validates :booking_date, presence: true
end

app/models/service.rb
class Service < ApplicationRecord
  GENRES = %w[Alternative Balada Banda-sinaloense Blues Children's Classical
              Dance Electronic Hip-Hop Instrumental Jazz Latin Mariachi
              New-age Opera Parody Pop Reggae Regional Religious Rock Vocal]
  belongs_to :user
  has_many :bookings, dependent: :destroy
  has_one_attached :photo

  validates :name, presence: true
  validates :rate, presence: true, numericality: { greater_than: 0 }
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  has_many :services
  has_many :bookings

  validates :user_type, presence: true, inclusion: { in: ["Artist", "Event host"] }
  validates :name, presence: true
  validates :email, uniqueness: true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :authenticate_user!
  before_action :configure_permitted_parameters, if: :devise_controller?
  # include Pundit

  # after_action :verify_authorized, except: :index, unless: :skip_pundit?
  # after_action :verify_policy_scoped, only: :index, unless: :skip_pundit?

  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:sign_up, keys: [:name, :user_type])
    devise_parameter_sanitizer.permit(:account_update, keys: [:first_name, :last_name])
  end
end

app/controllers/bookings_controller.rb
require 'date'
class BookingsController < ApplicationController

  def new
    @service = Service.find(params[:service_id])
    @booking = Booking.new
  end

  def create
    @booking = Booking.new(booking_params)
    @service = Service.find(params[:service_id])
    @booking.service = @service
    @amount = @booking.num_songs * @service.rate
    @booking.amount = @amount
    @booking.user = current_user
    # raise
    @booking.save!
    redirect_to bookings_path
  end

  def index
    if current_user.user_type == "Event host"
      @event_host_bookings = Booking.where(user: current_user)
    else
      @artist_bookings = Booking.joins(:service).where("services.user_id = ?", current_user.id)
    end
  end

  def show
    @booking = Booking.find(params[:id])
    @booking_date = @booking.booking_date.strftime('%a %d %b %Y')
  end

  def destroy
    @booking = Booking.find(params[:id])
    @booking.destroy
    redirect_to bookings_path
  end

  private

  def booking_params
    params.require(:booking).permit(:num_songs, :booking_date)
  end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  skip_before_action :authenticate_user!, only: :home

  def home
    @genres = %w[Alternative Balada Banda-sinaloense Blues Children's Classical
                 Dance Electronic Hip-Hop/Rap Instrumental Jazz Latin Mariachi
                 New-age Opera Parody Pop Reggae Regional Religious Rock Vocal]
  end
end

app/controllers/services_controller.rb
class ServicesController < ApplicationController

  def index
    @services = current_user.services
  end

  def show
    @service = Service.find(params[:id])
  end

  def genre
    @services = Service.where(name: params[:name][:name])
  end

  def new
    @genres = Service::GENRES
    @service = Service.new
  end

  def create
    @service = Service.new(service_params)
    @service.user = current_user
    if @service.save!
      redirect_to services_path
    else
      render "new"
    end
  end

  def edit
    @service = Service.find(params[:id])
  end

  def update
    @service = Service.find(params[:id])
    @service.update(service_params)
    redirect_to service_path(@service)
  end

  def destroy
    @service = Service.find(params[:id])
    @service.destroy if @service.user == current_user
    redirect_to services_path
  end

  # def destroy_pop
  #   pops = Service.where(name: 'Pop')
  #   pops.each.destroy
  # end
  # destroy_pop

  private

  def service_params
    params.require(:service).permit(:name, :rate, :photo, :demo_link)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/bookings/_artist_index.html.erb
<div class="grid">
  <% @artist_bookings.each do |booking|%>
    <div class="grid-item">
      <% if booking.service.photo.attached?  %>
        <%= cl_image_tag booking.service.photo.key %>
      <% else %>
        <img alt="image" src="https://images.unsplash.com/photo-1567361672830-f7aa558ec4e3?ixid=MnwxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8&ixlib=rb-1.2.1&auto=format&fit=crop&w=1170&q=80">
      <% end %>

      <div class="service-grid-info">
        <h4><%= booking.service.name %></h4>
        <p><%= "#{booking.num_songs} songs" %></p>
        <p><%= "#{booking.booking_date.strftime('%a %d %b %Y')}" %></p>
      </div>

      <%= link_to "See details", booking_path(booking), class: 'edit-service-button' %>
    </div>
  <% end %>
</div>

app/views/bookings/_event_host_index.html.erb
<div class="grid">
  <% @event_host_bookings.each do |booking|%>
    <div class="grid-item">
      <% if booking.service.photo.attached?  %>
        <%= cl_image_tag booking.service.photo.key %>
      <% else %>
        <img alt="image" src="https://images.unsplash.com/photo-1567361672830-f7aa558ec4e3?ixid=MnwxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8&ixlib=rb-1.2.1&auto=format&fit=crop&w=1170&q=80">
      <% end %>
      <div class="service-grid-info">
        <h4><%= booking.service.name %></h4>
        <p><%= "#{booking.num_songs} songs" %></p>
        <p><%= "#{booking.booking_date.strftime('%a %d %b %Y')}" %></p>
      </div>

      <%= link_to "See details", booking_path(booking), class: 'edit-service-button' %>
    </div>
  <% end %>
</div>

app/views/bookings/index.html.erb
<div class="main main-index">
  <div class="p-5">
    <h1 class="horizontal-line">Here are your upcoming bookings:</h1>

    <hr>

    <% if current_user.user_type == 'Event host' %>
      <%= render 'event_host_index' %>
    <% else %>
      <%= render 'artist_index' %>
    <% end %>
  </div>

</div>

app/views/bookings/new.html.erb
<div class="main">

  <div class="p-5 single-item">

    <div class="booking-content">
      <div>
        <% if @service.photo.attached?  %>
          <%= cl_image_tag @service.photo.key %>
        <% else %>
          <img alt="image" src="https://images.unsplash.com/photo-1567361672830-f7aa558ec4e3?ixid=MnwxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8&ixlib=rb-1.2.1&auto=format&fit=crop&w=1170&q=80">
        <% end %>
      </div>

      <div>
        <h2><%= @service.name %></h2>
        <h4><%= "$#{@service.rate}/hr" %></h4>
      </div>
  </div>

    <%= simple_form_for([@service, @booking]) do |f| %>
      <%= f.input :num_songs, :label => 'How many songs?', input_html: { min: 1 } %>
      <%= f.input :booking_date, as: :date, html5: true %>
      <%= f.submit 'Confirm booking' %>
    <% end %>
  </div>

</div>

app/views/bookings/show.html.erb
<div class="main service-index">
  <div class="service-show container">
    <h1 class="text-bold mb-4"><%= @booking.service.name %></h1>

    <div class="service-img">
      <% if @booking.service.photo.attached? %>
        <%= cl_image_tag @booking.service.photo.key %>
      <% else %>
        <img alt="image" src="https://images.unsplash.com/photo-1567361672830-f7aa558ec4e3?ixid=MnwxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8&ixlib=rb-1.2.1&auto=format&fit=crop&w=1170&q=80">
      <% end %>
    </div>

    <div class="horizontal-line"></div>

    <div class="mb-4 service-details">
      <h4><%= "Date: #{@booking_date}" %></h4>
      <h4><%= "#{@booking.num_songs} songs" %></h4>
      <h4>Rate per song: <span class="light">$<%= @booking.service.rate %></span></h4>
      <h4><%= "Total: $#{@booking.amount}" %></h4>
    </div>

    <% if current_user == @booking.user %>
      <%= link_to "Delete", booking_path(@booking), method: "delete", class: 'edit-service-button' %>
    <% end %>
    <%= link_to "All my bookings", bookings_path, class: 'edit-service-button' %>
  </div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Serenata</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%# Google Fonts Here %>
    <link rel="preconnect" href="https://fonts.googleapis.com">
    <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
    <link href="https://fonts.googleapis.com/css2?family=Noto+Sans:ital,wght@0,400;0,700;1,400;1,700&family=Noto+Serif+Display:ital,wght@0,300;0,400;0,600;1,300;1,400;1,600&display=swap" rel="stylesheet">

    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload', defer: true %>
  </head>

  <body>
    <%= render "shared/navbar" %>
    <%= yield %>

  <p class="notice"><%= notice %></p>
  <p class="alert"><%= alert %></p>
  <%= render "shared/flashes" %>

  </body>
</html>

app/views/pages/_artist_genres_form.html.erb
<%= simple_form_for :name, url: genre_services_path, method: :get do |f| %>
    <%= f.input :name, :label => 'Explore the magic of artists just like you',
                collection: Service::GENRES, :prompt => 'Select a genre' %>
    <%= f.submit 'Search' %>
<% end %>

app/views/pages/_event_host_genres_form.html.erb
<%= simple_form_for :name, url: genre_services_path, method: :get do |f| %>
    <%= f.input :name, :label => "Who's bringing your next party to life?",
                collection: Service::GENRES, :prompt => 'Select a genre' %>
    <%= f.submit 'Lets go' %>
<% end %>

app/views/pages/home.html.erb
<div class="main align-items-center d-flex" id="hero">
  <div class="hero-content container w-100 align-items-center text-center">

    <div class="hero-section justify-content-center">
      <h1 class="display-1 fw-bold">Live Music, On Demand</h1>
      <h2 class="display-5">Find and hire the best local musicians for your next event</h2>
    </div>

      <div class="justify-content-around hero-buttons d-flex">
        <% unless user_signed_in? %>
          <%= link_to "Log in", new_user_session_path, class: 'hero-button text-uppercase m-3 p-3 w-50 rounded-pill' %>
         <%= link_to "Sign up", new_user_registration_path, class: 'hero-button text-uppercase m-3 p-3 w-50 rounded-pill' %>
          <% else %>
            <% if user_signed_in? && current_user.user_type == 'Event host' %>
              <%= render 'event_host_genres_form' %>
            <% else %>
              <%= render 'artist_genres_form' %>
            <% end %>
        <% end %>
      </div>
  </div>
</div>

app/views/services/_services.html.erb
<div class="grid grid-index">
  <% @services.each do |service|%>
    <div class="grid-item">
      <% if service.photo.attached? %>
        <%= cl_image_tag service.photo.key %>
      <% else %>
        <img alt="image" src="https://images.unsplash.com/photo-1567361672830-f7aa558ec4e3?ixid=MnwxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8&ixlib=rb-1.2.1&auto=format&fit=crop&w=1170&q=80">
      <% end %>

      <div class="service-grid-info">
        <%= link_to service.user.name, service_path(service), class: 'text-bold' %>
        <%= "$#{service.rate}/song" %>
      </div>

      <% if current_user.user_type == 'Artist' %>
        <div class="edit-service-button"><%= link_to "See details", service_path(service), class: 'edit-service-link' %></div>
      <% else %>
        <div class="edit-service-button"><%= link_to "See details", service_path(service), class: 'edit-service-link' %></div>
        <div class="edit-service-button"><%= link_to "Book service", new_service_booking_path(service), class: 'edit-service-link' %></div>
      <% end %>
    </div>
  <% end %>
</div>

app/views/services/_your_services.html.erb
<div class="grid grid-index">
  <% @services.each do |service|%>
    <div class="grid-item">
      <% if service.photo.attached? %>
        <%= cl_image_tag service.photo.key %>
      <% else %>
        <img alt="image" src="https://images.unsplash.com/photo-1567361672830-f7aa558ec4e3?ixid=MnwxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8&ixlib=rb-1.2.1&auto=format&fit=crop&w=1170&q=80">
      <% end %>

      <div class="service-grid-info">
        <%= link_to service.name, service_path(service), class: 'text-bold' %>
        <%= "$#{service.rate}" %>
      </div>

      <% if current_user.user_type == 'Artist' %>
        <div class="edit-service-button"><%= link_to "See details", service_path(service), class: 'edit-service-link' %></div>
      <% else %>
        <div class="edit-service-button"><%= link_to "See details", service_path(service), class: 'edit-service-link' %></div>
        <div class="edit-service-button"><%= link_to "Book service", new_service_booking_path(service), class: 'edit-service-link' %></div>
      <% end %>
    </div>
  <% end %>
</div>

app/views/services/edit.html.erb
<div class="main">
  <div class="container">
    <h1><%= "Edit your #{@service.name} service" %></h1>

    <%= simple_form_for(@service) do |f| %>
      <%= f.input :name, collection: Service::GENRES, :placeholder => 'Select a genre' %>
      <%= f.input :rate, :label => 'Rate per song', input_html: { min: 1 } %>
      <%= f.input :demo_link, :label => 'Link to a demo video' %>
      <%= f.input :photo, as: :file, :label => 'Upload a photo' %>
      <%= f.submit "Update" %>
    <% end %>
  </div>

</div>

app/views/services/genre.html.erb
<div class="main main-index">
  <div class="p-5">
    <h1>Get inspired</h1>

    <h2>Search results for: <span class='light'><%= "#{params[:name][:name]} Musician Services"%></span></h2>
    <%= render 'services' %>
  </div>
</div>

app/views/services/index.html.erb
<div class="main main-index">
  <div class="p-5">
    <h1 class="mb-5">Your services</h1>
    <%= render 'your_services' %>
  </div>
</div>

app/views/services/new.html.erb
<div class="main">
  <div class="container">
    <h1 class="mb-4">Share your talent with the world. List your service.</h1>

    <p class="mb-4">Get booked by hundreds of event hosts near you</p>

    <%= simple_form_for([@user, @service]) do |f| %>
      <%= f.input :name, collection: Service::GENRES, :placeholder => 'Select a genre' %>
      <%= f.input :rate, :label => 'Rate per song', input_html: { min: 1 } %>
      <%= f.input :demo_link, :label => 'Link to a demo video' %>
      <%= f.input :photo, as: :file, :label => 'Upload a photo' %>
      <%= f.submit %>
    <% end %>
  </div>
</div>

app/views/services/show.html.erb
<div class="main main-index" id="service-show">
  <div class="service-show">
    <h1><span class="text-bold"><%= @service.name %></span> — <%= @service.user.name %></h1>

    <% if @service.photo.attached? %>
      <%= cl_image_tag @service.photo.key %>
    <% else %>
      <img alt="image" src="https://images.unsplash.com/photo-1567361672830-f7aa558ec4e3?ixid=MnwxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8&ixlib=rb-1.2.1&auto=format&fit=crop&w=1170&q=80">
    <% end %>

    <h4 class="m-3"><%= "$#{@service.rate}/song" %></h4>
    <%# For the JS injection %>
    <div id=demo-video>
    </div>
    <div class="mt-3">
      <%# <%= link_to 'Demo video', @service.demo_link, class: 'edit-service-button', target: "_blank", input_html: { target: '_blank' } %>
      <% if current_user.user_type == 'Event host' %>
        <%= link_to "Book service", new_service_booking_path(@service), class: 'edit-service-button' %>
      <% end %>

      <% if current_user == @service.user %>
        <%= link_to "Edit service", edit_service_path(@service), class: 'edit-service-button' %>
        <%= link_to "Delete", service_path(@service), method: "delete", class: 'edit-service-button' %>
      <% end %>
    </div>
  </div>
</div>

<%= javascript_tag do %>
  const embedVideo = (YTCode) => {
    const demo = document.querySelector("#demo-video");
    demo.insertAdjacentHTML("beforeend", YTCode);
  }

  embedVideo("<%= @service.demo_link.gsub(/"/,"'").html_safe %>")
<% end %>

app/views/shared/_avatar.html.erb
<% if current_user.user_type == 'Event host' %>
  <%= image_tag "host.PNG", class: "avatar dropdown-toggle", id: "navbarDropdown", data: { toggle: "dropdown" }, 'aria-haspopup': true, 'aria-expanded': false %>
<% else %>
  <%= image_tag "artist.PNG", class: "avatar dropdown-toggle", id: "navbarDropdown", data: { toggle: "dropdown" }, 'aria-haspopup': true, 'aria-expanded': false %>
<% end %>

app/views/shared/_flashes.html.erb
<% if notice %>
  <div class="alert alert-info alert-dismissible" role="alert">
    <button type="button" class="close" data-dismiss="alert" aria-label="Close"><span aria-hidden="true">&times;</span></button>
    <%= notice %>
  </div>
<% end %>
<% if alert %>
  <div class="alert alert-warning alert-dismissible" role="alert">
    <button type="button" class="close" data-dismiss="alert" aria-label="Close"><span aria-hidden="true">&times;</span></button>
    <%= alert %>
  </div>
<% end %>

app/views/shared/_navbar.html.erb
<div class="navbar navbar-expand-sm navbar-lewagon">
  <%= link_to "Serenata", root_path, class: "nav-link nav-logo" %>

  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>


  <div class="collapse navbar-collapse" id="navbarSupportedContent">
    <ul class="navbar-nav mr-auto">
      <li class="nav-item">
        <%= link_to "Home", root_path, class: "nav-link" %>
      </li>
      <% if user_signed_in? %>
        <li class="nav-item">
          <%= link_to "My bookings", bookings_path, class: "nav-link" %>
        </li>
        <li class="nav-item nav-link active" id="user-greeting">
          <%= "Hello, #{current_user.name}" %>
        </li>
        <li class="nav-item dropdown">
          <%= render 'shared/avatar' %>
          <div class="dropdown-menu dropdown-menu-right" aria-labelledby="navbarDropdown">
            <%= link_to "Log out", destroy_user_session_path, class: "dropdown-item", method: :delete %>
            <% if current_user.user_type == 'Event host' %>
              <%= link_to "List an event (Coming Soon)", root_path, class: "dropdown-item" %>
            <% else %>
              <%= link_to "My services", services_path, class: "dropdown-item" %>
              <%= link_to "Add a service", new_service_path, class: "dropdown-item" %>
            <% end %>
          </div>
        </li>
      <% else %>
        <%= link_to "Log In", new_user_session_path, class: "nav-link"  %>
        <%= link_to "Sign up", new_user_registration_path, class: "nav-link", id: "home-sign-up-nav" %>
      <% end %>
    </ul>
  </div>
</div>